# Generated by Django 2.1.3 on 2021-03-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pesquisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='nulo', max_length=200)),
                ('preco_parcelado', models.CharField(default='nulo', max_length=50)),
                ('preco_boleto', models.CharField(default='nulo', max_length=50)),
                ('data_inserida', models.DateField()),
            ],
        ),
    ]
