# Generated by Django 2.2.1 on 2021-03-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_equipamentos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamentos',
            name='nome',
        ),
        migrations.AddField(
            model_name='equipamentos',
            name='url',
            field=models.URLField(default='nulo', verbose_name='Link'),
        ),
    ]
