# Generated by Django 2.2.1 on 2021-03-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0003_auto_20210318_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesquisa',
            name='data_inserida',
            field=models.DateField(auto_now=True),
        ),
    ]
